export default [
    {
        name: "Harriet",
        age: "23",
        style: "Soul",
        location: "Southwark",
        studentPeriod: "6 months",
        pet: "Cat",
        food: "Chips",
        origin: "U.K.",
        color: "Red",
        hobby: "Make up artist",
        sport: "Yoga",
        languages: ["English", "German"],
        profession: "Software Developer",
        date: "10th December 2018",
        comment: "He has been my piano teacher for the last 6 months. I've learnt to pay attention to the details while studying, and keep time."
    },
    {
        name: "Fran",
        age: "25",
        style: "Jazz",
        location: "Bethnal Green",
        studentPeriod: "8 months",
        pet: "Hamster",
        food: "Pasta",
        origin: "Portugal",
        color: "Green",
        hobby: "Reading",
        sport: "Running",
        languages: ["Portuguese", "English"],
        profession: "Consultant",
        date: "12th January 2019",
        comment: "Xabi really helped me to improve my piano skills. He taught me how to improvise, a skill I never had until I met him."
    },
    {
        name: "James",
        age: "30",
        style: "Classical",
        location: "London Bridge",
        studentPeriod: "4 years",
        pet: "Dog",
        food: "Chicken",
        origin: "U.K.",
        color: "Purple",
        hobby: "Maths",
        sport: "Gym",
        languages: ["English", "Spanish"],
        profession: "Lawyer",
        date: "17th February 2019",
        comment: "I started doing the ABRSM grades with him three years ago and I couldn\'t be happier. He always encourages a positive attitude."
    },
    {
        name: "Dunia",
        age: "23",
        style: "Blues",
        location: "Kensington",
        studentPeriod: "2 years",
        pet: "Dog",
        food: "Hummus",
        origin: "Lebanon",
        color: "Pink",
        hobby: "Drawing",
        sport: "Stretching",
        languages: ["Arab", "English"],
        profession: "Software Developer",
        date: "22nd February 2019",
        comment: "He is a brilliant teacher. I have improved my musicality so much since I started his classes. Highly recommended!"
    },
    {
        name: "Ayush",
        age: "28",
        style: "Rock/Pop",
        location: "White Chapel",
        studentPeriod: "2 years",
        pet: "Snake",
        food: "pickles",
        origin: "India",
        color: "Brown",
        hobby: "Video games",
        sports: "Football",
        languages: ["English", "Hindi"],
        profession: "Doctor",
        date: "10th March 2019",
        comment: "He taught me how to play pop music and at the same time helped me improve my posture. I don't have back pain anymore!"
    },
    {
        name: "Chechi",
        age: "40",
        style: "Classical",
        location: "Westminster",
        studentPeriod: "1 year",
        pet: "Bird",
        food: "Roasted apples",
        origin: "Spain",
        color: "Black",
        hobby: "Cooking",
        sport: "Tennis",
        languages: ["Spanish","English"],
        profession: "Tourist Guide",
        date: "15th March 2019",
        comment: "We've studied together for a long time. He's patient and has a great knowledge of the instrument. He's very encouraging."
    },
    {
        name: "Anna",
        age: "28",
        style: "Classical",
        location: "London Bridge",
        studentPeriod: "8 months",
        pet: "turtle",
        food: "Smoked salmon",
        origin: "U.K.",
        color: "Blue",
        hobby: "Dancing",
        sport: "Swimming",
        languages: ["English","Spanish","German"],
        profession: "Lawyer",
        date: "5th April 2019",
        comment: "He is very versatile as a teacher. I learnt how to play jazz piano pieces with him and jazz harmony to make accompaniments."
    }
];